import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Toaster } from "~/components/ui/sonner"
import { SidebarInset, SidebarProvider, SidebarTrigger } from "~/components/ui/sidebar"
import { AppSidebar } from "~/components/app-sidebar"
import { ClerkProvider } from "@clerk/nextjs";
import { UserDisplay } from "~/components/user-display"
import { FlowgladProvider } from "@flowglad/nextjs"
import { currentUser } from "@clerk/nextjs/server"


export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const user = await currentUser()

  return (
    <ClerkProvider>
      <html lang="en" className={`${geist.variable}`}>
        <body>
          <FlowgladProvider loadBilling={!!user}>
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset>
                <header className="flex h-16 shrink-0 items-center justify-between border-b px-4">
                  <div className="flex items-center gap-2">
                    <SidebarTrigger className="-ml-1" />
                  </div>
                  <UserDisplay />
                </header>
                <div className="flex flex-1 flex-col gap-4 p-4">
                  {children}
                </div>
              </SidebarInset>
              <Toaster />
            </SidebarProvider>
          </FlowgladProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}


